---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-v1
  namespace: media
  labels:
    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
