---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bazarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/bazarr
      tag: 1.4.0@sha256:c81c4d9cbec093d5a999cfa3cd1af01d3f00d6292d6f5c33608510cef0ed83c7
    env:
      TZ: "${TIMEZONE}"
    service:
      main:
        ports:
          http:
            port: 6767
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "subtitles"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "bazarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "bazarr.${SECRET_DOMAIN}"
          secretName: "bazarr-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 1000
    persistence:
      config:
        enabled: true
        existingClaim: bazarr-config-v1
      media-storage:
        enabled: true
        existingClaim: nfs-media-storage-pvc
        mountPath: /media/storage/Media
    resources:
      requests:
        memory: 250Mi
        cpu: 10m
      limits:
        memory: 2000Mi
