---
apiVersion: v1
kind: Secret
metadata:
  name: auth-generic-oauth-secret
  namespace: monitoring
type: Opaque
stringData:
  client_id: grafana
  client_secret: ${SECRET_AUTHENTIK_GRAFANA_CLIENT_SECRET}

