---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.35.1
    env:
      TZ: "${TIMEZONE}"
      ZIGBEE2MQTT_DATA: /data
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "radio-tower"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: &host "zigbee.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
          secretName: "zigbee-tls"
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config-v1
        mountPath: "/data"
      usb:
        enabled: true
        type: hostPath
        mountPath: /dev/ttyACM0
        hostPath: /dev/ttyACM0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - {key: "feature.node.kubernetes.io/usb-02_0451_16a8.present", operator: In, values: ["true"]}
