---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zigbee2mqtt
      version: 9.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.28.2
    env:
      TZ: Asia/Jerusalem
      ZIGBEE2MQTT_DATA: /data
    config:
      homeassistant: true
      device_options:
        retain: true
      permit_join: false
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://vernemq"
        user: "nouserneeded"
        password: "nouserneeded"
      serial:
        port: /dev/ttyACM0
      advanced:
        log_output:
        - console
        pan_id: 25074
        network_key:
        - 28
        - 211
        - 223
        - 33
        - 54
        - 75
        - 160
        - 64
        - 116
        - 226
        - 85
        - 86
        - 166
        - 21
        - 232
        - 216
      frontend:
        port: 8080
      experimental:
        new_api: true
    securityContext:
      privileged: true
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "radio-tower"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-signin: https://authentik.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
          nginx.ingress.kubernetes.io/auth-url: http://authentik.networking.svc.cluster.local/outpost.goauthentik.io/auth/nginx
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "zigbee.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "zigbee.${SECRET_DOMAIN}"
          secretName: "zigbee-tls"
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-config-v1
        mountPath: "/data"
    additionalVolumeMounts:
    - name: usb
      mountPath: /dev/ttyACM0
    additionalVolumes:
    - name: usb
      hostPath:
        path: /dev/ttyACM0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - {key: "feature.node.kubernetes.io/custom-zigbee", operator: In, values: ["true"]}
    # addons:
    #   codeserver:
    #     enabled: true
    #     image:
    #       repository: codercom/code-server
    #       tag: 3.9.2
    #     workingDir: "/data"
    #     args:
    #     - --user-data-dir
    #     - "/data/.vscode"
    #     - --auth
    #     - "none"
    #     ingress:
    #       enabled: true
    #       annotations:
    #         kubernetes.io/ingress.class: "internal"
    #       hosts:
    #       - host: "zigbee2mqtt-config.${SECRET_DOMAIN}"
    #         paths:
    #         - path: /
    #           pathType: Prefix
    #       tls:
    #       - hosts:
    #         - "zigbee2mqtt-config.${SECRET_DOMAIN}"
    #     volumeMounts:
    #     - name: config
    #       mountPath: /data
