---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app lidarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/lidarr-develop
      tag: 2.1.2.3893@sha256:d9a03ed68017bf8674215836b1bc575182e16c7859918fac7068aec837ea81fd
    env:
      TZ: "${TIMEZONE}"
      LIDARR__INSTANCE_NAME: Lidarr
      LIDARR__PORT: &port 8686
      LIDARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "headphones"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "lidarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "lidarr.${SECRET_DOMAIN}"
          secretName: "lidarr-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 1000
    persistence:
      config:
        enabled: true
        existingClaim: lidarr-config-v1
      media-storage:
        enabled: true
        existingClaim: nfs-media-storage-pvc
        mountPath: /media/storage/Media
    resources:
      requests:
        memory: 250Mi
        cpu: 10m
      limits:
        memory: 1500Mi
