---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thelounge
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/thelounge/thelounge
      tag: 4.4.1
    env:
      THELOUNGE_HOME: "/config"
    service:
      main:
        ports:
          http:
            port: 9000
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "forum"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: &host "thelounge.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
          secretName: "thelounge-tls"
    persistence:
      config:
        enabled: true
        existingClaim: thelounge-config-v1
    resources:
      requests:
        memory: 250M
        cpu: 25m
      limits:
        memory: 500M
