---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thelounge
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: thelounge
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: thelounge/thelounge
      tag: 4.3.0-alpine
    
    env:
      THELOUNGE_HOME: "/config"
    ingress:
      main:
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: "https://raw.githubusercontent.com/thelounge/thelounge.github.io/master/assets/logos/logo/TL_Grey%26Yellow_Vertical_logotype_Transparent_Bg/TL_Grey%26Yellow_Vertical_logotype_Transparent_Bg.png"
          forecastle.stakater.com/network-restricted: "true"
        enabled: true
        ingressClassName: "traefik"
        hosts:
        - host: "thelounge.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "thelounge.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: thelounge-config-v1
