---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thelounge
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: thelounge
      version: 3.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: thelounge/thelounge
      tag: 4.3.0-alpine
    
    env:
      THELOUNGE_HOME: "/config"
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "forum"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "thelounge.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "thelounge.${SECRET_DOMAIN}"
          secretName: "thelounge-tls"
    persistence:
      config:
        enabled: true
        existingClaim: thelounge-config-v1
