---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wallabag
  namespace: media
data:
  themarker.com.txt: |
    http_header(user-agent): facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
    body: //div[@data-test="articleBody"]
    strip: //div[contains(@data-test, "tags")]
    strip: //ul[contains(@data-test, "relatedArticles")]

    find_string: data-src="https://
    replace_string: src="https://

    strip: //button
    tidy: no
    prune: no
  newmedia.calcalist.co.il.txt: |
    body: //div[@class='article-2021']

    strip: //div[@class='col-left']
    strip: //div[@class='hafnaya']
    strip: //div[@class='links-700']
    strip: //div[@class='hafnaya-con']

    tidy: no
    prune: no
