---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wallabag
  namespace: media
data:
  themarker.com.txt: |
    http_header(user-agent): facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)
    body: //div[@data-test="articleBody"]
