---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app wallabag
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: wallabag/wallabag
      tag: 2.5.4
      pullPolicy: IfNotPresent
    env:
      SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
      SYMFONY__ENV__DATABASE_HOST: wallabag-postgres-postgresql
      SYMFONY__ENV__DATABASE_PORT: 5432
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_USER: wallabag
      SYMFONY__ENV__DATABASE_PASSWORD: ${WALLABAG_POSTGRES_PASS}
      SYMFONY__ENV__DOMAIN_NAME: https://wallabag.${SECRET_DOMAIN}
      SYMFONY__ENV__SERVER_NAME: Wallabag
      SYMFONY__ENV__FOSUSER_REGISTRATION: "false"
      SYMFONY__ENV__FOSUSER_CONFIRMATION: "false"
      POPULATE_DATABASE: "false"
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "mdi:newspaper-variant"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host 'wallabag.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            secretName: "wallabag-tls"
    securityContext:
      runAsUser: 0
    persistence:
      custom-graby-config:
        enabled: true
        mountPath: /var/www/wallabag/vendor/j0k3r/graby-site-config/themarker.com.txt
        subPath: themarker.com.txt
        type: 'custom'
        volumeSpec:
          configMap:
            name: wallabag
      custom-graby-config2:
        enabled: true
        mountPath: /var/www/wallabag/vendor/j0k3r/graby-site-config/newmedia.calcalist.co.il.txt
        subPath: newmedia.calcalist.co.il.txt
        type: 'custom'
        volumeSpec:
          configMap:
            name: wallabag
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 512Mi
