---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app wallabag-postgres
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.5.9
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    auth:
      postgresPassword: ${WALLABAG_POSTGRES_ADMIN_PASS}
      username: wallabag
      password: ${WALLABAG_POSTGRES_PASS}
      database: wallabag
    primary:
      persistence:
        enabled: true
        existingClaim: wallabag-postgres-v1
