---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-postgres-v1
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
