---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wiki
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/volikon/wiki
      tag: 1.0.0@sha256:ce465dadc375a6ba68f7c38f0139bdf5106de310d34bf9fed539c8795e999dee
    imagePullSecrets:
    - name: ghcr-creds
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "wikipedia"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "wiki.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "wiki.${SECRET_DOMAIN}"
          secretName: "wiki-tls"
    resources:
      requests:
        cpu: 300m
        memory: 256M
      limits:
        memory: 512M
