---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: wiki
  namespace: flux-system
spec:
  image: ghcr.io/volikon/wiki
  interval: 1m0s
  secretRef:
    name: ghcr-creds
