---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: wiki
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: wiki
  filterTags:
    pattern: '^auto-(?P<ts>.*)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
