---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki-ingress
  namespace: home
  annotations:
    hajimari.io/enable: "true"
    hajimari.io/icon: "wikipedia"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - wiki.${SECRET_DOMAIN}
      secretName: "wiki-tls"
  rules:
    - host: wiki.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wiki
                port:
                  number: 80
