---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-v1
  namespace: media
  labels:
    kasten.io/backup-volume: "true"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: rook-ceph-block