---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/jellyfin
      tag: 10.8.8
    env:
      TZ: "Asia/Jerusalem"
    service:
      main:
        type: LoadBalancer
        externalIPs: ["${LB_JELLYFIN_IP}"]
        externalTrafficPolicy: Local
        ports:
          http:
            port: 8096
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "simple-icons:jellyfin"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: &host "jf.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
          secretName: "jf-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 44
        - 109
        - 100
    persistence:
      config:
        enabled: true
        existingClaim: jellyfin-config-v1
      media:
        enabled: true
        existingClaim: nfs-media-storage-pvc
        mountPath: /media/storage/Media
      transcode:
        enabled: false
    resources:
      requests:
        # gpu.intel.com/i915: 1
        cpu: 100m
        memory: 1000Mi
      limits:
        # gpu.intel.com/i915: 1
        memory: 4000Mi
