---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: 13.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2022.4.5
    env:
      TZ: "Asia/Jerusalem"
      HASS_RECORDER_POSTGRESQL: "${SECRET_POSTGRESQL_PASS}"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${LB_HOME_ASSISTANT_IP}"
        externalTrafficPolicy: Local
    ingress:
      main:
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: "https://raw.githubusercontent.com/home-assistant/frontend/a339de89f50a52170945728cdbcac1a2d11d433b/public/static/icons/favicon-192x192.png"
          forecastle.stakater.com/network-restricted: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "home-assistant"
        enabled: true
        ingressClassName: "traefik"
        hosts:
        - host: "ha.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "ha.${SECRET_DOMAIN}"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config-v1
    postgresql:
      enabled: true
      postgresqlPassword: "${SECRET_POSTGRESQL_PASS}"
      persistence:
        enabled: true
        size: 4Gi
        storageClass: "local-path"
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/k8s-at-home/code-server
          tag: v4.3.0
        # git:
        #   deployKeySecret: code-server
        workingDir: "/config"
        args:
        - --auth
        - "none"
        - --user-data-dir
        - "/config/.vscode"
        - --extensions-dir
        - "/config/.vscode"
        ingress:
          annotations:
            forecastle.stakater.com/expose: "true"
            forecastle.stakater.com/icon: "https://raw.githubusercontent.com/home-assistant/frontend/a339de89f50a52170945728cdbcac1a2d11d433b/public/static/icons/favicon-192x192.png"
            forecastle.stakater.com/network-restricted: "true"
            hajimari.io/enable: "true"
            hajimari.io/icon: "home-edit"
          enabled: true
          ingressClassName: "traefik"
          hosts:
          - host: "ha-vscode.${SECRET_DOMAIN}"
            paths:
            - path: /
              pathType: Prefix
          tls:
          - hosts:
            - "ha-vscode.${SECRET_DOMAIN}"
        volumeMounts:
        - name: config
          mountPath: /config
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        memory: 4000Mi
