---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: robot-shop
  namespace: dev
spec:
  interval: 15m
  chart:
    spec:
      chart: robot-shop
      version: 0.1.4
      sourceRef:
        kind: HelmRepository
        name: robot-shop-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations: 
        cert-manager.io/cluster-issuer: letsencrypt-production
        nginx.ingress.kubernetes.io/rewrite-target: /$2
      host: shop.efk8s.com
