---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    crds:
      enabled: false
    controller:
      image:
        repository: quay.io/metallb/controller
        tag: v0.13.6
    speaker:
      image:
        repository: quay.io/metallb/speaker
        tag: v0.13.5
