---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: group-manager-bot
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/jonatan1609/group-manager-bot
      tag: 1.0.8
    controller:
      replicas: 1
    nameOverride: group-manager-bot
    env:
      CONFIG_FILE: "/config/config.toml"
    persistence:
      config:
        enabled: true
        existingClaim: group-manager-bot-config-v1
    service:
      main:
        enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
