apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress-nginx-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- grafana-charts.yaml
- kasten-charts.yaml
- kubernetes-sigs-descheduler-charts.yaml
- node-feature-discovery-charts.yaml
- prometheus-community-charts.yaml
- rook-ceph-charts.yaml
- vernemq-charts.yaml
- metallb-charts.yaml
- lwolf-charts.yaml
- weaveworks-kured-charts.yaml
