---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app home-assistant
  namespace: home
spec:
  values:
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.10.1
        env:
          TZ: "${TIMEZONE}"
        workingDir: /config
        args:
          - --auth
          - "none"
          - --user-data-dir
          - "/config/.vscode"
          - --extensions-dir
          - "/config/.vscode"
        ingress:
          annotations:
            hajimari.io/enable: "true"
            hajimari.io/icon: "home-edit"
            hajimari.io/appName: "HA-Editor"
            cert-manager.io/cluster-issuer: "letsencrypt-production"
          enabled: true
          ingressClassName: "nginx"
          hosts:
            - host: &host "ha-vscode.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host
              secretName: "ha-vscode-tls"
        volumeMounts:
          - name: config
            mountPath: /config
