---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentik-postgresql-v1
  namespace: networking
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
