---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 2022.11.0
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2022.11.1
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        hajimari.io/enable: "true"
        hajimari.io/icon: "key-variant"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      hosts:
      - host: authentik.${SECRET_DOMAIN}
        paths:
        - path: /
      tls:
      - hosts:
        - "authentik.${SECRET_DOMAIN}"
        secretName: "authentik-tls"
    authentik:
      secret_key: ${AUTHENTIK_SECRET_KEY}
      log_level: debug
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      postgresql:
        host: '{{ .Release.Name }}-postgresql'
        name: authentik
        user: authentik
        password: ${AUTHENTIK_POSTGRES_PASSWORD}
      redis:
        host: '{{ .Release.Name }}-redis-master'
        password: ${AUTHENTIK_REDIS_PASSWORD}
    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: authentik-postgresql-v1
      postgresqlUsername: authentik
      postgresqlDatabase: authentik
      postgresqlPassword: ${AUTHENTIK_POSTGRES_PASSWORD}
    redis:
      enabled: true
      auth:
        enabled: true
        password: ${AUTHENTIK_REDIS_PASSWORD}


