---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.goauthentik.io
      chart: authentik
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2021.10.4
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        forecastle.stakater.com/expose: "true"
        forecastle.stakater.com/icon: "https://raw.githubusercontent.com/goauthentik/authentik/983747b13b94782f4d06340497062a1bc77d78c5/website/static/img/icon.png"
        forecastle.stakater.com/network-restricted: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "key-variant"
      hosts:
      - host: authentik.${SECRET_DOMAIN}
        paths:
        - path: /
      tls:
      - hosts:
        - "authentik.${SECRET_DOMAIN}"
    authentik:
      secret_key: ${AUTHENTIK_SECRET_KEY}
      log_level: debug
      outposts:
        docker_image_base: ghcr.io/goauthentik/%(type)s:%(version)s
      postgresql:
        host: '{{ .Release.Name }}-postgresql'
        name: authentik
        user: authentik
        password: ${AUTHENTIK_POSTGRES_PASSWORD}
      redis:
        host: '{{ .Release.Name }}-redis-master'
        password: ${AUTHENTIK_REDIS_PASSWORD}
    postgresql:
      enabled: true
      persistence:
        enabled: true
        existingClaim: authentik-postgresql-v1
      postgresqlUsername: authentik
      postgresqlDatabase: authentik
      postgresqlPassword: ${AUTHENTIK_POSTGRES_PASSWORD}
    redis:
      enabled: true
      auth:
        enabled: true
        password: ${AUTHENTIK_REDIS_PASSWORD}


