---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyload-config-v1
  namespace: media
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
