---
kind: Profile
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: minio
  namespace: kasten-io
spec:
  locationSpec:
    type: ObjectStore
    objectStore:
      endpoint: "http://10.0.40.51:9000"
      name: k10
      objectStoreType: S3
      path: k10/51cbf22b-af99-4571-ac19-07eae74598de/migration
      pathType: Directory
    credential: # aws_access_key_id, aws_secret_access_key
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: secret
        name: k10secret-64sws
        namespace: kasten-io
  type: Location
status:
  validation: Success
  hash: 4055781777
