---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.0.40.70-10.0.40.79
  INGRESS_NGINX_LB: 10.0.40.70
  LB_HOME_ASSISTANT_IP: 10.0.40.71
  LB_VERNEMQ_IP: 10.0.40.71
  LB_JELLYFIN_IP: 10.0.40.72
