---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: prowlarr
      version: 4.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/prowlarr-nightly
      tag: v0.4.7.2048
    env:
      TZ: "Asia/Jerusalem"
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-search"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "prowlarr.${SECRET_DOMAIN}"
            secretName: "prowlarr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: prowlarr-config-v1
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 1000Mi
