---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.4.5@sha256:f78bda4a40b8c8734fba09e65b4553a8be89e88f746db614fe04a83ece1b817e
    env:
      TZ: "Asia/Jerusalem"
      QBITTORRENT__PORT: &port 80
      QBITTORRENT__BT_PORT: &port-bt 50413
    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        enabled: true
        type: LoadBalancer
        externalIPs: ["${LB_QBITTORRENT_IP}"]
        ports:
          bittorrent:
            enabled: true
            port: *port-bt
            protocol: TCP
            targetPort: *port-bt
        externalTrafficPolicy: Local
    ingress:
      main:
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: "https://raw.githubusercontent.com/qbittorrent/qBittorrent/master/src/icons/qbittorrent.ico"
          forecastle.stakater.com/network-restricted: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "cloud-download"
        enabled: true
        ingressClassName: "traefik"
        hosts:
        - host: &host "qb.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 1000
    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
      media-storage:
        enabled: true
        existingClaim: nfs-media-storage-pvc
        mountPath: /media/storage/Media
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 4000Mi
    metrics:
      enabled: true
      serviceMonitor:
        interval: 1m
        scrapeTimeout: 10s
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: esanchezm/prometheus-qbittorrent-exporter
          tag: v1.2.0
        env:
          user: "nevo"
          password: "${QBITTORRENT_PASSWORD}"
          port: 9022
          logLevel: INFO
