---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.9.1549
    env:
      TZ: "Asia/Jerusalem"
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-signin: https://authentik.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
          nginx.ingress.kubernetes.io/auth-url: http://authentik.networking.svc.cluster.local/outpost.goauthentik.io/auth/nginx
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "sonarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sonarr.${SECRET_DOMAIN}"
          secretName: "sonarr-tls"
      # additionalIngresses:
      # - enabled: true
      #   nameSuffix: "api"
      #   hosts:
      #   - host: "sonarr.${SECRET_DOMAIN}"
      #     paths:
      #     - path: /api
      #       pathType: Prefix
      #   tls:
      #   - hosts:
      #     - "sonarr.${SECRET_DOMAIN}"
    podSecurityContext:
      supplementalGroups:
      - 1000
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.1.0
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: false
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      media-storage:
        enabled: true
        existingClaim: nfs-media-storage-pvc
        mountPath: /media/storage/Media
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 1500Mi
