---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 13.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1265
    env:
      TZ: "Asia/Jerusalem"
    ingress:
      main:
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: "https://raw.githubusercontent.com/Sonarr/Sonarr/4659a8366d8a1565890d3b72442bd35c6eb8176e/Logo/128.png"
          forecastle.stakater.com/network-restricted: "true"
        enabled: true
        hosts:
        - host: "sonarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sonarr.${SECRET_DOMAIN}"
      # additionalIngresses:
      # - enabled: true
      #   nameSuffix: "api"
      #   hosts:
      #   - host: "sonarr.${SECRET_DOMAIN}"
      #     paths:
      #     - path: /api
      #       pathType: Prefix
      #   tls:
      #   - hosts:
      #     - "sonarr.${SECRET_DOMAIN}"
    podSecurityContext:
      supplementalGroups:
      - 1000
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      media-storage:
        enabled: true
        existingClaim: nfs-media-storage-pvc
        mountPath: /media/storage/Media
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
    prometheus:
      podMonitor:
        enabled: true
        interval: 10m
        scrapeTimeout: 2m
    additionalContainers:
    - name: exportarr
      image: ghcr.io/onedr0p/exportarr:v0.6.1
      imagePullPolicy: IfNotPresent
      args: ["exportarr", "sonarr"]
      env:
      - name: PORT
        value: "32123"
      - name: URL
        value: "http://localhost"
      - name: CONFIG
        value: "/config/config.xml"
      - name: ENABLE_UNKNOWN_QUEUE_ITEMS
        value: "true"
      - name: ENABLE_ADDITIONAL_METRICS
        value: "true"
      ports:
      - name: exportarr
        containerPort: 32123
      volumeMounts:
      - name: config
        mountPath: /config
        readOnly: true
