---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app sonarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/onedr0p/sonarr-develop
      tag: 4.0.2.1408@sha256:e539aa15ecc8edec3ea68eb95aa784a15e941b2904920d70bb419c15d59a0d06
    env:
      TZ: "${TIMEZONE}"
      SONARR__INSTANCE_NAME: Sonarr
      SONARR__PORT: &port 8989
      SONARR__LOG_LEVEL: info
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "television-box"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-signin: https://authentik.${SECRET_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme://$host$request_uri
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
          nginx.ingress.kubernetes.io/auth-url: http://authentik.networking.svc.cluster.local/outpost.goauthentik.io/auth/nginx
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: "sonarr.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "sonarr.${SECRET_DOMAIN}"
          secretName: "sonarr-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 1000
    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      media-storage:
        enabled: true
        existingClaim: nfs-media-storage-pvc
        mountPath: /media/storage/Media
    resources:
      requests:
        memory: 250Mi
        cpu: 10m
      limits:
        memory: 1500Mi
