---
apiVersion: v1
kind: Service
metadata:
  name: pve
  namespace: networking
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pve
  namespace: networking
subsets:
  - addresses:
      - ip: 10.0.40.50
      - ip: 10.0.40.52
      - ip: 10.0.40.53
    ports:
      - port: 8006
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pve-ingress
  namespace: networking
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://forum.proxmox.com/styles/uix/images/Proxmox-logo-stacked-white-background-1200.png"
    forecastle.stakater.com/network-restricted: "true"
spec:
  tls:
    - hosts:
        - pve.${SECRET_DOMAIN}
  rules:
    - host: pve.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pve
                port:
                  number: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: octoprint
  namespace: networking
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: octoprint
  namespace: networking
subsets:
  - addresses:
      - ip: 10.0.0.150
    ports:
      - port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: octoprint-ingress
  namespace: networking
  annotations:
    forecastle.stakater.com/expose: "true"
    forecastle.stakater.com/icon: "https://docs.octoprint.org/en/1.5.3/_images/octoprint-logo.png"
    forecastle.stakater.com/network-restricted: "true"
  #   nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - octoprint.${SECRET_DOMAIN}
  rules:
    - host: octoprint.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: octoprint
                port:
                  number: 80
