---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files-v1
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
