---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vikunja
      version: 6.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    caddy:
      noTls: true
    vikunja:
      config: "service:\n jwtsecret: \"${SECRET_VIKUNJA_JWT_SECRET}\"\n timezone: \"Asia/Jerusalem\""
    image:
      repository: caddy
      tag: 2.6.2-alpine
      pullPolicy: IfNotPresent
    controllerType: deployment
    strategy:
      type: Recreate
    service:
      main:
        port:
          port: 8080
        annotations:
          prometheus.io/probe: "true"
          prometheus.io/protocol: http
    additionalContainers:
      - name: api
        image: vikunja/api:0.20.1
        env:
          - name: VIKUNJA_DATABASE_TYPE
            value: "postgres"
          - name: VIKUNJA_DATABASE_HOST
            value: vikunja-postgresql
          - name: VIKUNJA_DATABASE_DATABASE
            value: vikunja
          - name: VIKUNJA_DATABASE_USER
            value: vikunja
          - name: VIKUNJA_DATABASE_PASSWORD
            value: ${SECRET_VIKUNJA_POSTGRES_PASSWORD}
        volumeMounts:
          - name: files
            mountPath: /app/vikunja/files
          - name: config
            mountPath: /app/vikunja/config.yml
            subPath: config.yml
            readOnly: true
      - name: frontend
        image: vikunja/frontend:0.20.3
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "format-list-checks"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: tasks.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tasks.${SECRET_DOMAIN}"
            secretName: "tasks-tls"
    persistence:
      files:
        enabled: true
        existingClaim: vikunja-files-v1
        mountpath: /app/vikunja/files
      config:
        enabled: true
        type: custom
        readOnly: true
        mountPath: "-"
        volumeSpec:
          configMap:
            name: vikunja-config-yml
    postgresql:
      auth:
        postgresPassword: ${SECRET_VIKUNJA_POSTGRES_ADMIN_PASSWORD}
        username: vikunja
        password: ${SECRET_VIKUNJA_POSTGRES_PASSWORD}
        database: vikunja
      enabled: true
      persistence:
        enabled: true
        existingClaim: vikunja-postgres-v1
