---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vikunja
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: vikunja
      version: 5.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    caddy:
      noTls: true
    vikunja:
      config: "service:\n jwtsecret: \"${SECRET_VIKUNJA_JWT_SECRET}\"\n timezone: \"Asia/Jerusalem\""
    image:
      repository: caddy
      tag: 2.5.1-alpine
      pullPolicy: IfNotPresent
    controllerType: deployment
    strategy:
      type: Recreate
    service:
      main:
        port:
          port: 8080
        annotations:
          prometheus.io/probe: "true"
          prometheus.io/protocol: http
    additionalContainers:
      - name: api
        image: vikunja/api:0.19.2
        env:
          - name: VIKUNJA_DATABASE_TYPE
            value: "postgres"
          - name: VIKUNJA_DATABASE_HOST
            value: vikunja-postgresql
          - name: VIKUNJA_DATABASE_DATABASE
            value: vikunja
          - name: VIKUNJA_DATABASE_USER
            value: vikunja
          - name: VIKUNJA_DATABASE_PASSWORD
            value: ${SECRET_VIKUNJA_POSTGRES_PASSWORD}
        volumeMounts:
          - name: files
            mountPath: /app/vikunja/files
          - name: config
            mountPath: /app/vikunja/config.yml
            subPath: config.yml
            readOnly: true
      - name: frontend
        image: vikunja/frontend:0.18.2
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/appName: "Vikunja"
          forecastle.stakater.com/icon: "https://vikunja.io/docs/images/vikunja-logo-white.svg"
          forecastle.stakater.com/network-restricted: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "format-list-checks"
        hosts:
          - host: tasks.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "tasks.${SECRET_DOMAIN}"
    persistence:
      files:
        enabled: true
        existingClaim: vikunja-files-v1
        mountpath: /app/vikunja/files
      config:
        enabled: true
        type: custom
        readOnly: true
        mountPath: "-"
        volumeSpec:
          configMap:
            name: vikunja-config-yml
    postgresql:
      postgresqlPostgresPassword: ${SECRET_VIKUNJA_POSTGRES_ADMIN_PASSWORD}
      postgresqlUsername: vikunja
      postgresqlPassword: ${SECRET_VIKUNJA_POSTGRES_PASSWORD}
      postgresqlDatabase: vikunja
      enabled: true
      persistence:
        enabled: true
        existingClaim: vikunja-postgres-v1
