---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: apps
  namespace: kasten-io
spec:
  frequency: "@daily"
  retention:
    daily: 4
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - home
      - media
  actions:
  - action: backup
    backupParameters:
      filters:
        includeResources:
        - resource: persistentvolumeclaims
          matchExpressions:
          - key: kasten.io/backup-volume
            operator: In
            values:
            - "true"
        profile:
          name: nfs
          namespace: kasten-io
  - action: export
    exportParameters:
      frequency: "@daily"
      receiveString: bIzAPpoanmEDniRwrRpxvpZFe28+MmvEhy6J8nJ9e694P9JojzvheYGkZ8eim6BmHzXGzKuNGU+u7zELhTr9j2UpsgAZMNDKQrWv3OK1lc61qK1YpWxpYxiZzZKJUqBwfowGmmAbi9p/mbOQ7NzDlV2qD9zV+hJ41XHqIHDOkOWLw7pTEnfUm1GiqziOKg1a+rBdTdn/mVhq00o3MTiL9929XXSzHSjrpihO/IrbWJdep4bOOnTYbsUDs6SuidqyZJbfJa+PK9pzW2/4vBon4DLZ9f/TMqvHjFTNDG5wWWRnX3/J9GQi5Gf5rZOA4dB9wQx6avxBjXM5gsU4n3yDVKJY86ZSYhINqM12xNGqsav7hB3SgNfZhH1p0wry3zxj/IAq2katcZ8SzHza8XZXqAd5
      profile:
        name: nfs
        namespace: kasten-io
      migrationToken:
        name: apps-migration-token-vqhgc
        namespace: kasten-io
      exportData:
        enabled: true
    retention: {}
