---
kind: Policy
apiVersion: config.kio.kasten.io/v1alpha1
metadata:
  name: k10-disaster-recovery-policy
  namespace: kasten-io
spec:
  frequency: "@hourly"
  retention:
    hourly: 4
    daily: 0
    weekly: 0
    monthly: 0
    yearly: 0
  selector:
    matchExpressions:
    - key: k10.kasten.io/appNamespace
      operator: In
      values:
      - kasten-io
  actions:
  - action: backup
    backupParameters:
      filters: {}
      profile:
        name: minio
        namespace: kasten-io
