---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    updateStrategy: RollingUpdate
    configuration:
      startTime: "1:00"
      endTime: "3:00"
      timeZone: "Asia/Jerusalem"
      notifyUrl: "${SECRET_KURED_SLACK_URL}"
    tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
    metrics:
      create: true
