---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app calibre-web
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.21@sha256:f333c996ef247eec9ad6ff328018e589b42117cdc6643ae65938daa605655235
    env:
      TZ: "${TIMEZONE}"
      CACHE_DIR: /cache
    enableServiceLinks: false
    service:
      main:
        ports:
          http:
            port: 8083
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "book-open"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: &host "calibre-web.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
          secretName: "calibre-web-tls"
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
      - 1000
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-v1
      books:
        enabled: true
        type: nfs
        server: "10.0.40.50"
        path: /media/storage/Media/Books
        mountPath: /media/storage/Media/Books
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache
    resources:
      requests:
        cpu: 15m
        memory: 249M
      limits:
        memory: 299M