---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: group-manager-bot-db-v1
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
