---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: group-manager-bot-db
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 10.5.3
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    postgresqlUsername: group-manager-bot
    postgresqlPassword: ${GROUP_MANAGER_BOT_DB_PASS}
    postgresqlDatabase: group-manager-bot
    persistence:
      enabled: true
      existingClaim: group-manager-bot-db-v1
      size: 1Gi
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi
