---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  releaseName: node-red
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/node-red
      tag: v2.1.3
    env:
      TZ: "Asia/Jerusalem"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    persistence:
      data:
        enabled: true
        existingClaim: nodered-config-v1
    ingress:
      main:
        annotations:
          forecastle.stakater.com/expose: "true"
          forecastle.stakater.com/icon: "https://nodered.org/about/resources/media/node-red-icon-2.png"
          forecastle.stakater.com/network-restricted: "true"
        enabled: true
        ingressClassName: "traefik"
        hosts:
        - host: "nodered.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "nodered.${SECRET_DOMAIN}"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
