---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset
    image:
      repository: docker.io/nodered/node-red
      tag: 3.1.0
    env:
      TZ: "${TIMEZONE}"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    service:
      main:
        ports:
          http:
            port: 1880
    ingress:
      main:
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "resistor-nodes"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        enabled: true
        ingressClassName: "nginx"
        hosts:
        - host: &host "nodered.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - *host
          secretName: "nodered-tls"
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      fsGroupChangePolicy: "OnRootMismatch"
    persistence:
      config:
        enabled: true
        existingClaim: nodered-config-v1
        mountPath: "/data"
    resources:
      requests:
        memory: 164M
        cpu: 25m
      limits:
        memory: 262M
