---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-kasten
spec:
  storageClassName: kasten
  capacity:
    storage: 1Mi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.40.50
    path: /media/storage/Backup/kasten
  mountOptions:
  - nfsvers=4.1
  - hard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-kasten
  namespace: kasten-io
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: kasten
  resources:
    requests:
      storage: 1Mi
