---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
spec:
  serviceAccountName: system-upgrade
  concurrency: 1
  channel: https://update.k3s.io/v1-release/channels/v1.27
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: In
        values:
          - "true"
      - key: k3s-upgrade
        operator: In
        values:
          - "true"
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
  prepare:
    # Defaults to the same "resolved" tag that is used for the `upgrade` container, NOT `latest`
    image: rancher/k3s-upgrade
    args: ["prepare", "k3s-server"]
  upgrade:
    image: rancher/k3s-upgrade
